### ISSUE TITLE
Inline styling

### ISSUE THREAD

**Issue by ghost** [srose30206/prj-rev-bwfs-dasmoto#5]
https://github.com/srose30206/prj-rev-bwfs-dasmoto/blob/master/DasMoto/index.html#L21

Avoid writing inline styles.

You should just give the `span` tag a class like `price` or `pricing` and then just apply the styles in your CSS file.

**Comment by srose30206** [comment]
I'm sorry,  I looked at the highlighted code but don't understand the issue. Thanks.

**Comment by srose30206** [comment]
Hi.  I looked at the highlighted code, but I don't understand the issue. thanks.
