### ISSUE TITLE
Image alt attributes

### ISSUE THREAD

**Issue by ghost** [srose30206/prj-rev-bwfs-dasmoto#6]
https://github.com/srose30206/prj-rev-bwfs-dasmoto/blob/master/DasMoto/index.html#L18

Make sure to give your `img` tags an `alt` attribute. Give it a value that adequately describes the image, just in case your website is not able to load it.

Doing so will help improve the accessibility of your website, which might be accessed by visually impaired users on e-readers or other devices that might deliberately neglect images-- as well as any other time that your website is just unable to render images.

**Comment by srose30206** [comment]
yes.  I learned about this yesterday. thanks.
