### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [srose30206/prj-rev-bwfs-dasmoto#8]
Needs Improvement

It looks like you've got a good handle on CSS properties, have mostly reproduced the design we provided you.

Your code needs to be improved. You need to make more strategic use of the `div` element to the divide your code into logical sections and you need to make your CSS readable by another human being or otherwise you're going to have a lot of trouble updating and maintaining your code. Make sure to avoid writing inline styles and instead follow conventions as taught in the program.

**Comment by srose30206** [comment]
Hi.  Maybe I overlooked it.  Are there specific comments in the code itself?  Thanks
